# Generated by Django 4.1 on 2022-11-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Verduras', 'Verduras'), ('Frutas', 'Frutas'), ('Panaderia', 'Panaderia'), ('Carniceria', 'Carniceria'), ('Otros', 'Otros')], default='Otros', max_length=200),
        ),
    ]
